// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniMap.Api.Data;

#nullable disable

namespace UniMap.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927100027_UseDailyCardNameInChats")]
    partial class UseDailyCardNameInChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniMap.Api.Domain.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AboutId")
                        .HasColumnType("uuid")
                        .HasColumnName("about_id");

                    b.Property<string>("AboutType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("about_type");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_conversation_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("policy_version");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("UserId", "PolicyVersion", "Type", "CreatedAt")
                        .HasDatabaseName("ix_consent_records_user_id_policy_version_type_created_at");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<DateTimeOffset?>("UserALastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_a_last_read_at");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.Property<DateTimeOffset?>("UserBLastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_b_last_read_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_conversations_user_b_id");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_user_a_id_user_b_id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.DailyDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<DateTimeOffset?>("DrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drawn_at");

                    b.Property<Guid?>("MatchedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_user_id");

                    b.Property<bool>("SessionRestart")
                        .HasColumnType("boolean")
                        .HasColumnName("session_restart");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_draws");

                    b.HasIndex("MatchedUserId")
                        .HasDatabaseName("ix_daily_draws_matched_user_id");

                    b.HasIndex("Day", "DrawnAt")
                        .HasDatabaseName("ix_daily_draws_day_drawn_at");

                    b.HasIndex("UserId", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_draws_user_id_day");

                    b.ToTable("daily_draws", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("award_type");

                    b.PrimitiveCollection<List<string>>("Campuses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("campuses");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("college");

                    b.Property<bool>("IsDoubleDegree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_double_degree");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("university");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_degrees");

                    b.HasIndex("University", "Level", "College")
                        .HasDatabaseName("ix_degrees_university_level_college");

                    b.HasIndex("University", "Level", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_degrees_university_level_name");

                    b.ToTable("degrees", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.EventAttendee", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("EventId", "UserId")
                        .HasName("pk_event_attendees");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_attendees_user_id");

                    b.ToTable("event_attendees", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.FlatListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<string>("Bathroom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("bathroom");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<int>("BillsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("bills_per_week");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<int>("Flatmates")
                        .HasColumnType("integer")
                        .HasColumnName("flatmates");

                    b.Property<string>("Furnished")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("furnished");

                    b.PrimitiveCollection<List<string>>("HouseRhythm")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("house_rhythm");

                    b.PrimitiveCollection<List<string>>("Housemates")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("housemates");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<int?>("MinStayMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_stay_months");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.PrimitiveCollection<List<string>>("PhotoKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("photo_keys");

                    b.Property<string>("PreferredFlatmate")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("preferred_flatmate");

                    b.Property<int>("RentPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("rent_per_week");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("street");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("suburb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("Toilet")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("toilet");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flat_listings");

                    b.HasIndex("Features")
                        .HasDatabaseName("ix_flat_listings_features");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Features"), "gin");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_flat_listings_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_flat_listings_owner_id");

                    b.HasIndex("Status", "RentPerWeek")
                        .HasDatabaseName("ix_flat_listings_status_rent_per_week");

                    b.ToTable("flat_listings", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.MarketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("availability");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("condition");

                    b.Property<string>("ConditionNote")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("condition_note");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.PrimitiveCollection<List<string>>("PhotoKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("photo_keys");

                    b.Property<string>("PickupPointId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pickup_point_id");

                    b.Property<string>("PlaceName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("place_name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_market_items");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_market_items_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("PickupPointId")
                        .HasDatabaseName("ix_market_items_pickup_point_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_market_items_seller_id");

                    b.HasIndex("Availability", "Category", "CreatedAt")
                        .HasDatabaseName("ix_market_items_availability_category_created_at");

                    b.ToTable("market_items", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.MeetupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("place_id");

                    b.Property<string>("PlaceName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("place_name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WalkInsWelcome")
                        .HasColumnType("boolean")
                        .HasColumnName("walk_ins_welcome");

                    b.HasKey("Id")
                        .HasName("pk_meetup_events");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_meetup_events_host_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_meetup_events_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_meetup_events_starts_at");

                    b.ToTable("meetup_events", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AgeRange")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("age_range");

                    b.Property<string>("AvatarIcon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("avatar_icon");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_key");

                    b.Property<string>("AvatarMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("avatar_mode");

                    b.Property<int?>("AvatarPreset")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_preset");

                    b.Property<string>("AvatarRing")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("avatar_ring");

                    b.Property<string>("AvatarShape")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("avatar_shape");

                    b.Property<string>("AvatarText")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("avatar_text");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer")
                        .HasColumnName("degree_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.PrimitiveCollection<List<string>>("Habits")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("habits");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<string>("Nationality")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("nationality")
                        .IsFixedLength();

                    b.Property<string>("Pronouns")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pronouns");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.HasIndex("DegreeId")
                        .HasDatabaseName("ix_profiles_degree_id");

                    b.HasIndex("Habits")
                        .HasDatabaseName("ix_profiles_habits");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Habits"), "gin");

                    b.HasIndex("Interests")
                        .HasDatabaseName("ix_profiles_interests");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Interests"), "gin");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("university");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.ChatMessage", b =>
                {
                    b.HasOne("UniMap.Api.Domain.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("UniMap.Api.Domain.ConsentRecord", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniMap.Api.Domain.Conversation", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_user_a_id");

                    b.HasOne("UniMap.Api.Domain.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_users_user_b_id");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("UniMap.Api.Domain.DailyDraw", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "MatchedUser")
                        .WithMany()
                        .HasForeignKey("MatchedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_daily_draws_users_matched_user_id");

                    b.HasOne("UniMap.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_draws_users_user_id");

                    b.Navigation("MatchedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniMap.Api.Domain.EventAttendee", b =>
                {
                    b.HasOne("UniMap.Api.Domain.MeetupEvent", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_attendees_meetup_events_event_id");

                    b.HasOne("UniMap.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_attendees_users_user_id");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniMap.Api.Domain.FlatListing", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flat_listings_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UniMap.Api.Domain.MarketItem", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_items_users_seller_id");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("UniMap.Api.Domain.MeetupEvent", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetup_events_users_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("UniMap.Api.Domain.Profile", b =>
                {
                    b.HasOne("UniMap.Api.Domain.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_profiles_degrees_degree_id");

                    b.HasOne("UniMap.Api.Domain.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("UniMap.Api.Domain.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("Degree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniMap.Api.Domain.MeetupEvent", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("UniMap.Api.Domain.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
