// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniMap.Api.Data;

#nullable disable

namespace UniMap.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926072506_AddFlatListings")]
    partial class AddFlatListings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniMap.Api.Domain.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("award_type");

                    b.PrimitiveCollection<List<string>>("Campuses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("campuses");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("college");

                    b.Property<bool>("IsDoubleDegree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_double_degree");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("university");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_degrees");

                    b.HasIndex("University", "Level", "College")
                        .HasDatabaseName("ix_degrees_university_level_college");

                    b.HasIndex("University", "Level", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_degrees_university_level_name");

                    b.ToTable("degrees", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.FlatListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<string>("Bathroom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("bathroom");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<int>("BillsPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("bills_per_week");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<int>("Flatmates")
                        .HasColumnType("integer")
                        .HasColumnName("flatmates");

                    b.Property<string>("Furnished")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("furnished");

                    b.PrimitiveCollection<List<string>>("HouseRhythm")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("house_rhythm");

                    b.PrimitiveCollection<List<string>>("Housemates")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("housemates");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<int?>("MinStayMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_stay_months");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.PrimitiveCollection<List<string>>("PhotoKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("photo_keys");

                    b.Property<string>("PreferredFlatmate")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("preferred_flatmate");

                    b.Property<int>("RentPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("rent_per_week");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("street");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("suburb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("Toilet")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("toilet");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flat_listings");

                    b.HasIndex("Features")
                        .HasDatabaseName("ix_flat_listings_features");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Features"), "gin");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_flat_listings_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_flat_listings_owner_id");

                    b.HasIndex("Status", "RentPerWeek")
                        .HasDatabaseName("ix_flat_listings_status_rent_per_week");

                    b.ToTable("flat_listings", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AgeRange")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("age_range");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<int?>("DegreeId")
                        .HasColumnType("integer")
                        .HasColumnName("degree_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.PrimitiveCollection<List<string>>("Habits")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("habits");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<string>("Nationality")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("nationality")
                        .IsFixedLength();

                    b.Property<string>("Pronouns")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pronouns");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.HasIndex("DegreeId")
                        .HasDatabaseName("ix_profiles_degree_id");

                    b.HasIndex("Habits")
                        .HasDatabaseName("ix_profiles_habits");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Habits"), "gin");

                    b.HasIndex("Interests")
                        .HasDatabaseName("ix_profiles_interests");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Interests"), "gin");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("university");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UniMap.Api.Domain.FlatListing", b =>
                {
                    b.HasOne("UniMap.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flat_listings_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UniMap.Api.Domain.Profile", b =>
                {
                    b.HasOne("UniMap.Api.Domain.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_profiles_degrees_degree_id");

                    b.HasOne("UniMap.Api.Domain.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("UniMap.Api.Domain.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("Degree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniMap.Api.Domain.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
